// Login
export const LoginData = {
    en: {
        welcomeBack: "Welcome back",
        loginText: "Login to your LMS account",
        identifierLabel: "Email, Username, or Phone",
        identifierPlaceholder: "Enter your email, username, or phone",
        passwordLabel: "Password",
        forgotPassword: "Forgot your password?",
        stayLoggedIn: "Stay logged in",
        signIn: "Sign In",
        orContinueWith: "Or continue with",
        loginWithGoogle: "Login with Google",
        noAccount: "Don't have an account?",
        signUp: "Sign up",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
    },
    ar: {
        welcomeBack: "مرحبًا بعودتك",
        loginText: "قم بتسجيل الدخول إلى حسابك في LMS",
        identifierLabel: "البريد الإلكتروني أو اسم المستخدم أو الهاتف",
        identifierPlaceholder:
            "أدخل بريدك الإلكتروني أو اسم المستخدم أو رقم الهاتف",
        passwordLabel: "كلمة المرور",
        forgotPassword: "هل نسيت كلمة المرور؟",
        stayLoggedIn: "البقاء متصلاً",
        signIn: "تسجيل الدخول",
        orContinueWith: "أو تابع باستخدام",
        loginWithGoogle: "تسجيل الدخول باستخدام Google",
        noAccount: "ليس لديك حساب؟",
        signUp: "سجل",
        termsOfService: "شروط الخدمة",
        privacyPolicy: "سياسة الخصوصية",
    },
    fr: {
        welcomeBack: "Content de vous revoir",
        loginText: "Connectez-vous à votre compte LMS",
        identifierLabel: "Email, Nom d'utilisateur ou Téléphone",
        identifierPlaceholder: "Entrez votre email, nom d'utilisateur ou téléphone",
        passwordLabel: "Mot de passe",
        forgotPassword: "Mot de passe oublié ?",
        stayLoggedIn: "Rester connecté",
        signIn: "Se connecter",
        orContinueWith: "Ou continuez avec",
        loginWithGoogle: "Se connecter avec Google",
        noAccount: "Vous n'avez pas de compte ?",
        signUp: "S'inscrire",
        termsOfService: "Conditions d'utilisation",
        privacyPolicy: "Politique de confidentialité",
    },
};

// Register
export const RegisterData = {
    en: {
        createAccount: "Create an account",
        signUp: "Sign up for your LMS account",
        name: "Name*",
        email: "Email*",
        password: "Password*",
        confirmPassword: "Confirm Password*",
        username: "Username",
        phone: "Phone",
        signUpButton: "Sign Up",
        orContinueWith: "Or continue with",
        loginWithGoogle: "Login with Google",
        alreadyHaveAccount: "Already have an account?",
        logIn: "Log in",
        termsAndConditions: "Terms of Service",
        privacyPolicy: "Privacy Policy",
    },
    ar: {
        createAccount: "إنشاء حساب",
        signUp: "اشترك في حساب LMS الخاص بك",
        name: "الاسم*",
        email: "البريد الإلكتروني*",
        password: "كلمة المرور*",
        confirmPassword: "تأكيد كلمة المرور*",
        username: "اسم المستخدم",
        phone: "الهاتف",
        signUpButton: "سجل",
        orContinueWith: "أو تابع باستخدام",
        loginWithGoogle: "تسجيل الدخول باستخدام Google",
        alreadyHaveAccount: "هل لديك حساب بالفعل؟",
        logIn: "تسجيل الدخول",
        termsAndConditions: "شروط الخدمة",
        privacyPolicy: "سياسة الخصوصية",
    },
    fr: {
        createAccount: "Créer un compte",
        signUp: "Inscrivez-vous pour votre compte LMS",
        name: "Nom*",
        email: "E-mail*",
        password: "Mot de passe*",
        confirmPassword: "Confirmer le mot de passe*",
        username: "Nom d'utilisateur",
        phone: "Téléphone",
        signUpButton: "S'inscrire",
        orContinueWith: "Ou continuez avec",
        loginWithGoogle: "Se connecter avec Google",
        alreadyHaveAccount: "Vous avez déjà un compte ?",
        logIn: "Se connecter",
        termsAndConditions: "Conditions d'utilisation",
        privacyPolicy: "Politique de confidentialité",
    },
};

// ForgetPassword
export const ForgetPasswordData = {
    en: {
        title: "Forgot Password",
        subtitle: "Enter your email to reset your password",
        emailLabel: "Email",
        emailPlaceholder: "m@example.com",
        resetButton: "Reset Password",
        rememberPassword: "Remember your password?",
        backToLogin: "Back to Login",
    },
    fr: {
        title: "Mot de passe oublié",
        subtitle: "Entrez votre email pour réinitialiser votre mot de passe",
        emailLabel: "E-mail",
        emailPlaceholder: "m@exemple.com",
        resetButton: "Réinitialiser le mot de passe",
        rememberPassword: "Vous vous souvenez de votre mot de passe ?",
        backToLogin: "Retour à la connexion",
    },
    ar: {
        title: "نسيت كلمة المرور",
        subtitle: "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور",
        emailLabel: "البريد الإلكتروني",
        emailPlaceholder: "m@example.com",
        resetButton: "إعادة تعيين كلمة المرور",
        rememberPassword: "هل تذكر كلمة المرور؟",
        backToLogin: "العودة إلى تسجيل الدخول",
    },
};

// ResetPassword
export const ResetPasswordData = {
    en: {
        newPasswordLabel: "New Password",
        confirmPasswordLabel: "Confirm New Password",
        newPasswordPlaceholder: "Enter your new password",
        confirmPasswordPlaceholder: "Confirm your new password",
        resetPasswordButton: "Reset Password",
    },
    fr: {
        newPasswordLabel: "Nouveau mot de passe",
        confirmPasswordLabel: "Confirmer le nouveau mot de passe",
        newPasswordPlaceholder: "Entrez votre nouveau mot de passe",
        confirmPasswordPlaceholder: "Confirmez votre nouveau mot de passe",
        resetPasswordButton: "Réinitialiser le mot de passe",
    },
    ar: {
        newPasswordLabel: "كلمة المرور الجديدة",
        confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
        newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
        confirmPasswordPlaceholder: "تأكيد كلمة المرور الجديدة",
        resetPasswordButton: "إعادة تعيين كلمة المرور",
    },
};

// CheckCode
export const CheckCodeData = {
    en: {
        title: "Reset Your Password",
        subtitleCodeSuccess: "Enter your new password",
        subtitleEnterCode: "Enter the code you received",
        resendCode: "Resend Code",
        submitCode: "Submit Code",
    },
    fr: {
        title: "Réinitialiser votre mot de passe",
        subtitleCodeSuccess: "Entrez votre nouveau mot de passe",
        subtitleEnterCode: "Entrez le code que vous avez reçu",
        resendCode: "Renvoyer le code",
        submitCode: "Soumettre le code",
    },
    ar: {
        title: "إعادة تعيين كلمة المرور",
        subtitleCodeSuccess: "أدخل كلمة المرور الجديدة الخاصة بك",
        subtitleEnterCode: "أدخل الرمز الذي تلقيته",
        resendCode: "إعادة إرسال الرمز",
        submitCode: "إرسال الرمز",
    },
};